FROM mcr.microsoft.com/mssql/server:2022-latest

RUN mkdir /var/opt/mssql/bin
COPY ./publish/sqlclr/myVector.dll /var/opt/mssql/bin

USER root
RUN chown mssql:mssql /var/opt/mssql/bin --recursive

USER mssql

CMD ["/opt/mssql/bin/sqlservr"]
